version: "3.8"

services:
  db.sqlserver:
    container_name: "${DB_HOST:-db.sqlserver}"
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "${DB_PORT:-1433}:${DB_PORT:-1433}"
    user: "root"
    volumes:
      - "./volumes/db/sqlserver:/var/opt/mssql/data"
    environment:
      - "MSSQL_SA_PASSWORD=${DB_PASS:-Admin_1234}"
      - "MSSQL_TCP_PORT=${DB_PORT:-1433}"
    env_file: "./.env"

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "${RABBITMQ_PORT:-5672}:${RABBITMQ_PORT:-5672}"
      - "${RABBITMQ_MANAGEMENT_TCP_LISTEN_PORT:-15672}:${RABBITMQ_MANAGEMENT_TCP_LISTEN_PORT:-15672}"
    volumes:
      - "./volumes/messagebus/rabbit:/var/lib/rabbitmq/mnesia"
    env_file: "./.env"

  rediscache:
    image: "redis:latest"
    container_name: "${REDIS_HOST}"
    restart: "always"
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
    volumes:
      - "./volumes/cache/redis/data:/root/redis"
      - "./volumes/cache/redis/redis.conf:/usr/local/etc/redis/redis.conf"
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD:-Admin_1234}"]
    env_file: "./.env"