version: "3.8"

services:  
  nginx_webapi:
      container_name: "nginx_webapi"
      build:
        context: "./SocialNetworkApi"
        dockerfile: "/Dockerfile_nginx"
      ports:
        - "${WEB_API_PORT:-7129}:${NGINX_WEBAPI_INNER_PORT:-8081}"
      depends_on:
        - "webapi"
      restart: "always"
      env_file: "./.env"
      command: "/bin/sh -c \"envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'\""

  nginx_webui:
      container_name: "nginx_webui"
      build:
        context: "./UIApp"
        dockerfile: "/Dockerfile_nginx"
      ports:
        - "${WEB_UI_PORT:-7054}:${NGINX_WEBUI_INNER_PORT:-8080}"
      depends_on:
        - "webui"
      restart: "always"
      env_file: "./.env"
      command: "/bin/sh -c \"envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'\""

  nginx_authapi:
      container_name: "nginx_authapi"
      build:
        context: "./AuthApi"
        dockerfile: "/Dockerfile_nginx"
      ports:
          - "${AUTH_API_PORT:-7006}:${NGINX_AUTHAPI_INNER_PORT:-8082}"
      depends_on:
          - "authapi"
      restart: "always"
      env_file: "./.env"
      command: "/bin/sh -c \"envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'\""