version: '3.4'

services:

  # webui:
  #   image: ${DOCKER_REGISTRY-}webui
  #   container_name: "${WEB_UI_HOST:-webui}"
  #   build:
  #     context: .
  #     dockerfile: WebUI/Dockerfile
  #   depends_on:
  #     - webapi
  #   environment:
  #     - ASPNETCORE_URLS=https://+:${WebUIPort:-80}
  #   ports:
  #     - "${WebUIPort:-80}:${WebUIPort:-80}"
  #   env_file: './.env'

  # webapi:
  #   image: ${DOCKER_REGISTRY-}webapi
  #   container_name: "${WEB_API_HOST:-webapi}"
  #   build:
  #     context: .
  #     dockerfile: WebApi/Dockerfile
  #   depends_on:
  #     - authapi
  #     - db.sqlserver
  #   environment:
  #     - "ASPNETCORE_URLS=https://+:${WebApiPort:-81}"
  #   ports:
  #     - "${WebApiPort}:${WebApiPort:-81}" 
  #   env_file: './.env'

  # authapi:
  #   container_name: "${AUTH_API_HOST:-authapi}"
  #   image: ${DOCKER_REGISTRY-}authapi
  #   build:
  #     context: .
  #     dockerfile: AuthApi/Dockerfile
  #   depends_on:
  #     - db.sqlserver.auth
  #   environment:
  #     - ASPNETCORE_URLS=https://+:${AuthApiPort:-82}
  #   ports:
  #     - "${AuthApiPort:-82}:${AuthApiPort:-82}"
  #   env_file: './.env'

  db.sqlserver:
    container_name: "${DB_HOST:-db.sqlserver}"
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "${DB_PORT:-1433}:${DB_PORT:-1433}"
    user: root
    volumes:
      - './volumes/db/sqlserver:/var/opt/mssql/data'
    environment:
      - MSSQL_SA_PASSWORD=${DB_PASS:-Admin_1234}
      - MSSQL_TCP_PORT=${DB_PORT:-1433}
    env_file: './.env'

  db.sqlserver.auth:
    container_name: "${DB_AUTH_HOST:-db.sqlserver.auth}"
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "${DB_AUTH_PORT:-1411}:${DB_AUTH_PORT:-1411}"
    user: root
    volumes:
      - './volumes/db/authsqlserver:/var/opt/mssql/data'
    environment:
      - MSSQL_SA_PASSWORD=${DB_AUTH_PASS:-Admin_1234}
      - MSSQL_TCP_PORT=${DB_AUTH_PORT:-1411}
    env_file: './.env'

  db.sqlserver.hangfirejobs:
    container_name: "${DB_HANGFIRE_HOST:-db.sqlserver.hangfirejobs}"
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "${DB_HANGFIRE_PORT:-1444}:${DB_HANGFIRE_PORT:-1444}"
    user: root
    volumes:
      - './volumes/db/hangfire:/var/opt/mssql/data'
    environment:
      - MSSQL_SA_PASSWORD=${DB_HANGFIRE_PASS:-Admin_1234}
      - MSSQL_TCP_PORT=${DB_HANGFIRE_PORT:-1444}
    env_file: './.env'

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "${RABBITMQ_PORT:-5672}:${RABBITMQ_PORT:-5672}"
      - "${RABBITMQ_MANAGEMENT_TCP_LISTEN_PORT:-15672}:15672"
    volumes:
      - './volumes/messagebus/rabbit:/var/lib/rabbitmq/mnesia' 
    env_file: './.env'

  rediscache:
    image: redis:latest
    container_name: "${REDIS_HOST}"
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
    volumes:
      - './volumes/cache/redis/data:/root/redis'
      - './volumes/cache/redis/redis.conf:/usr/local/etc/redis/redis.conf'
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD:-Admin_1234}"]
    env_file: './.env'
