IF NOT EXISTS (SELECT * FROM master.dbo.sysdatabases q WHERE q.[name] = 'DB_HANGFIRE_JOBS') 
BEGIN 
CREATE DATABASE [DB_HANGFIRE_JOBS]; 
END; 

IF NOT EXISTS (SELECT * FROM master.dbo.sysdatabases q WHERE q.[name] = 'SEQ') 
BEGIN 
CREATE DATABASE [SEQ]; 
END;